# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cloud test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: mium
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: miumdatabase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - run: npm ci

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql://mium:${{ secrets.DB_PASSWORD }}@localhost:5432/miumdatabase?schema=public" >> $GITHUB_ENV

    - name: Run Prisma migrations
      run: npm run migrate:dev:init -w apps/cloud/

    - name: Generate Prisma client
      run: npm run prisma:generate -w apps/cloud/

    - name: Run tests
      run: npm test -w apps/cloud/