name: Image build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the podman image
      run: podman build . --file Dockerfile --tag my-image-name:$(date +%s)
